name: PR Template
about: Describe the purpose or the changes made in this PR.

# Labels for categorization
labels:
  - enhancement
  - bug
  - documentation

# Assignees for the PR
assignees:
  - username1
  - username2

# Reviewers for the PR
reviewers:
  - username3
  - username4

# Projects associated with this PR
projects:
  - ProjectName1
  - ProjectName2

# Milestone for this PR
milestone: MilestoneName

# Description of the PR
description: |
  Brief description of the changes made in this PR.

  ## Changes Made
  - Change 1
  - Change 2

# Checklist for contributors to follow
checklist:
  - [ ] Tests added/passed
  - [ ] Documentation updated
  - [ ] Code follows style guidelines
