name: 🐞 버그 리포트
description: 버그 발생 시 해당 내용을 상세하게 리포트 해주세요 😉
title: "[Bug]: "
labels: [bug]
body:
- type: textarea
  attributes:
    label: 버그 설명
    description: 발생한 버그를 간단하게 설명해주세요 🤑
    placeholder: |
      - A class 작업 시 DB 트랜잭션이 안되는 문제 발생
  validations:
    required: true

- type: textarea
  attributes:
    label: 스크린샷 
    description: 에러 로그나 문제의 코드의 스크린샷이 있다면 첨부해주세요 📷
    placeholder: 로그, 코드 등의 이미지 파일
  validations:
    required: false

- type: textarea
  attributes:
    label: 예상 원인
    description: 버그 발생 원인이 추정된다면 그 부분을 설명해주세요 🔎
    placeholder: 코드에 오타가 있는 것으로 추정됨
  validations:
    required: false

- type: textarea
  attributes:
    label: 버그 발생 과정
    description: 버그가 발생될 때까지의 실행 과정을 알려주세요 🕹
    placeholder: |
      뭐시기 API를 실행했는데...
      DB의 이런저런 테이블을 업데이트 했는데...
      버그가 발생했어요...
  validations:
    required: false

- type: textarea
  attributes:
    label: 추가 사항
    description: |
      Links? References? Ideas? 문제 해결을 위한 다른 사항들을 남겨주세요 😁
  validations:
    required: false

- type: checkboxes
  attributes:
    label: 버그 리포팅 전 체크 리스트 🐞
    options:
      - label: 이 버그와 관련된 사람을 assigness로 등록했나요?
        required: true
      - label: 다른 사람의 도움이 필요한 경우 help wanted 태그를 첨부했나요?
        required: true
      - label: 버그 내용을 성실하게 기입했나요?
        required: true
