name: Python Formatting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Poetry
      run: pipx install poetry
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.1"
        cache: "poetry"
    - run: poetry install
    - name: Formatting with black
      run: black --check .
